joints:
  # Configuration for all joints
  # First 8 are the left arm, from shoulder to wrist
  # Second 8 are the right arm, from shoulder to wrist
  
  # Offsets are in degrees, and are multiples of 90
  offsets:
    - 180
    - 180
    - 180
    - 90
    - 360 
    - 270
    - 90
    - -90
    - 180 
    - 180
    - 270
    - 90
    - 360
    - 90
    - 180
    - 180

  signs: [-1, 1, -1, 1, 1, 1, 1, 1, -1, 1, -1, 1, 1, 1, -1, 1]